import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { getCurrentUser } from "./actions/getCurrentUser";
import Script from "next/script";
import DebugPageLog from "@/components/debug/DebugPageLog";
import Toast from "@/components/Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar currentUser={currentUser} />
        <Toast />
        {children}
        <Script src="//dapi.kakao.com/v2/maps/sdk.js?appkey=59d6694dbbc782911f85b944e451af38&libraries=services,clusterer&autoload=false" />
        { 
          (process.env.DEBUG === 'true') &&
          <DebugPageLog />
        }
      </body>
    </html>
  );
}
